### ISSUE TITLE
New link format: branch name only (no commit)

### ISSUE THREAD

**Issue by placetobejohan** [reduckted/GitWebLinks#138]
This is a feature request to include a 4th link format **branch only**. This format only contains the branch name and not the commit SHA, eg https://bitbucket.org/myworkspace/myrepo/src/main/README.md.

This would be useful for providing permanent links to files with changing content but unchanging location.

**Comment by reduckted** [comment]
Hmm, that's Interesting. That _should_ be the "default branch" format, but it looks like the Bitbucket Cloud link format is out of date. They must have updated the format at some point in the last couple of years so that you don't have to specify the SHA anywhere in the URL. Shouldn't be too hard to update.

**Comment by reduckted** [comment]
I've made a change in 7c0bf4e93d1c383153921d4bbe446d6436324cfa where Bitbucket Cloud URLs will use new new link format where possible (branch names that contain a forward slash still have to use the old format). 

It's published as v2.9.3 on the marketplace. Can you try it out and see if the "default branch" format gives you the style of link that you're after?
