### ISSUE TITLE
Link gives 404 even when user is signed-in to GitHub

### ISSUE THREAD

**Issue by robryan** [reduckted/GitWebLinks#6]
### Expected behavior
If a user is … 
- signed-in to GitHub
- has access to a private repo

… then you can:

1. right click in VSCode on a line of code in that private repo you have access to
2. click `Copy Web Link to Selection`
3. paste that link in the browser
4. see the line of code in your GitHub tab

### Actual behavior
In the `.gif` below you'll see I am a user who … 

- signed-in to GitHub
- have access to my private repo (proven here by showing side-by-side of the GitHub code tab + VSCode code file)

then I … 

1. right click in VSCode on a line of code in my repo
2. click `Copy Web Link to Selection`
3. paste that link in the browser
4. get a `404` error

![bug report showing 404 error](https://user-images.githubusercontent.com/212360/84423514-6b028d80-abd3-11ea-9902-276fe31b11bd.gif)

to confirm this isn't an access issue, afterward I:

5. navigate to the same code file using the GitHub web UI
6. copy the permalink using a vanilla UI element `Copy permalink`
7. paste that link in a new tab, which works (no `404` error)

### To reproduce
1. Confirm you are signed-in to GitHub and you have access to some repo `A` with code file `B`
2. right click in VSCode on a line of code in code file `B`
3. click `Copy Web Link to Selection`
4. paste that link in the browser
5. get a `404` error
6. now for comparison navigate to the `Code` tab in GitHub for repo `A`
7. search manually for code file `B` to confirm it exists and you can access it

**Comment by reduckted** [comment]
Thanks for the awesome reproduction steps!

It looks like the hash in the URL is different between what the extension produced and what the GitHub permalink produced. What I suspect has happened is you have commits in your local repository that have not been pushed to the GitHub remote.

There are two types of links that this extension can produce. Both have their advantages and disadvantages.

The default type is `"hash"` and will create a link using the current commit. This is great for producing permalinks, but unfortunately it can lead to 404s if your current commit hasn't been pushed to the remote.

The other type is `"branch"` and will create a link using the current branch. This is good if you only need the link to be useful for a short period of time, but it's not great for producing permalinks since the link only points to a branch, and the code on that branch can change in the future.

You can change the setting by searching for "link type" in the settings UI:

![image](https://user-images.githubusercontent.com/10321525/84491828-83180100-ace8-11ea-92ae-c1e9abba490f.png)

Or, if you prefer editing the settings as JSON, you can set the `"gitweblinks.linkType"` setting to either `"hash"` or `"branch"`.

![image](https://user-images.githubusercontent.com/10321525/84492061-e86bf200-ace8-11ea-85d0-1cd1f697b98a.png)

As an example, here are the two types of links to the `package.json` in this repository:

Using `"hash"`:
https://github.com/reduckted/vscode-gitweblinks/blob/ba945ebfd0553d49e0e862cf845230c9f29efdff/package.json

Using `"branch"` (when on the master branch):
https://github.com/reduckted/vscode-gitweblinks/blob/master/package.json
